name: OtherDrops
main: com.gmail.zariust.otherdrops.OtherDrops
version: 3.2.7
author: Zarius
authors: [Updated by CoolLord22]
website: https://www.spigotmc.org/resources/otherdrops-updated.51793/
commands:
    od:
        description: Administrate the OtherDrops plugin
        aliases: [otherdrops, odreload, odr, odshow, ods, ode, o, odd, odi, odst, odt, odc, odw]
        usage: |
            §aOtherDrops §7(configure anything to drop anything) 
            §7Version: 3.2.7-Beta
            §7(§a/odr§7) §a/od reload §7- reload config
            §7(§a/odi§7) §a/od id §7- show data values for item held in hand
            §7(§a/odw§7) §a/od write §7- writes data values for item held in hand to ItemOutput.txt file
            §7(§a/odd§7) §a/od drop <string> §7- parse the string and drop relevant item/mob
            §a/od §7(§aenable§7|§adisable§7) - turn OtherDrops on or off (will reset on server reload)
            §a/od show <block> §7- show custom drops for particular blocktype
            §a/od settings §7- show current global settings

softdepend:
  - WorldGuard
  - Towny
  - NoCheatPlus
  - GriefPrevention
  - Vault
  - Multiverse-Core
  - CoreProtect
  - Jobs
  - WildStacker
  - MythicMobs
permissions:
permissions:
    otherdrops.admin.id:
        default: op
        description: Gives permission to ID items (show name@data) and write the item data to the output file.
    otherdrops.admin.reloadconfig:
        default: op
        description: Gives permission to reload the config files for OtherDrops.
    otherdrops.admin.show:
        default: op
        description: Gives permission to show the registered drops.
    otherdrops.admin.drop:
        default: op
        description: Gives permission to use drop command (/odd).
    otherdrops.admin.enabledisable:
        default: op
        description: Gives permission to turn OtherDrops on and off.
